version: "3.7"
services:
## https://hybris.ecaassite.cloudspc.it
## https://vote-result2.ecaashackathon.cloudspc.it 
  hybris:
    container_name: hybris
    image: angegar/hybris:latest
    labels:
      - "com.dxc.ecaas.friendlyname=hybris"
    environment:
      - HYBRIS_DB_URL=jdbc:mysql://hybris-db:3306/hybriscommerce?useConfigs=maxPerformance&characterEncoding=utf8
      - HYBRIS_DB_DRIVER=com.mysql.jdbc.Driver
      - HYBRIS_DB_USER=hybris
      - HYBRIS_DB_PASSWORD=hybris
      - HYBRIS_INITIALIZE_SYSTEM=yes
    ports:
      - "80:9001"
      - "9002:9002"
      - "8983:8943"
      - "8000:8000"
    #logging:
    #  driver: syslog
    #  options:
    #    syslog-address: "udp://172.17.0.1:6515"
    #    syslog-format: "rfc5424micro"
    #    tag: "hybris/hybris"

    networks: 
      - frontend
      - backend
    depends_on:
      - hybris-db
    deploy:
      labels:
        - ecaas.external.port=443
        - ecaas.external.host=hybris
        - com.docker.ucp.access.label=/Shared/ecaas
      mode: replicated
      replicas: 2
      #update_config:
      #  parallelism: 2
      #  delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: '4'
          memory: 20gb
        limits:
          cpus: '5'
          memory: 32gb
      placement:
        constraints: [node.labels.engine==worker]

  hybris-db:
    container_name: hybris-db
    image: stefanlehmann/hybris-mysql:latest
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.17.0.1:6515"
        syslog-format: "rfc5424micro"
        tag: "hybris/hybris-db"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hybris
    deploy:
      placement:
          constraints: [node.labels.engine==worker]
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data:
    external: true