FROM ubuntu:18.04

#RUN  apt-get update && apt-get install -y software-properties-common \
#    && add-apt-repository -y ppa:webupd8team/java \
#    && apt-get update \
#    && apt-get install -y oracle-java8-installer

RUN apt-get update \
    && apt-get -y install software-properties-common \
    && add-apt-repository -y ppa:webupd8team/java \
    && echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections \
    && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections \
    && apt-get update \
    && apt-get -y install oracle-java8-installer  \